global:
  resolve_timeout: 5m

route:
  receiver: local-alertmanager-ui
  group_by:
    - alertname
    - severity
    - service
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 4h

receivers:
  - name: local-alertmanager-ui
